// <auto-generated />
using GymManagement_Promo_Microservice.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymManagement_Promo_Microservice.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251018234836_PromoAnnotationsRemove")]
    partial class PromoAnnotationsRemove
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gym_SaaS_Microservices.Models.Promo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<decimal>("Discount")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<int>("MonthDuration")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Promo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "22ABT",
                            Discount = 0.50m,
                            MonthDuration = 3
                        },
                        new
                        {
                            Id = 2,
                            Code = "23H5F",
                            Discount = 0.20m,
                            MonthDuration = 6
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
