// <auto-generated />
using System;
using GymManagement_MemberShips_Microservice.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymManagement_MemberShips_Microservice.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251022170851_PaymentHistory")]
    partial class PaymentHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GymManagement_MemberShips_Microservice.Models.MemberSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DebitActive")
                        .HasColumnType("bit");

                    b.Property<string>("IBAN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("PaymentDay")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasAlternateKey("MemberId")
                        .HasName("AK_MemberSubscription_MemberId");

                    b.HasIndex("MemberId")
                        .IsUnique();

                    b.ToTable("MemberSubscriptions");
                });

            modelBuilder.Entity("GymManagement_MemberShips_Microservice.Models.PaymentHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IBAN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("CAST(GETDATE() AS date)");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("PaymentHistory");
                });

            modelBuilder.Entity("GymManagement_MemberShips_Microservice.Models.PaymentHistory", b =>
                {
                    b.HasOne("GymManagement_MemberShips_Microservice.Models.MemberSubscription", "MemberSubscription")
                        .WithMany("PaymentHistories")
                        .HasForeignKey("MemberId")
                        .HasPrincipalKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MemberSubscription");
                });

            modelBuilder.Entity("GymManagement_MemberShips_Microservice.Models.MemberSubscription", b =>
                {
                    b.Navigation("PaymentHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
